---
driver:
  name: vagrant
  require_chef_omnibus: true

platforms:
  - name: ark_server
    driver_config:
      box: bento/centos-7.1
      vm_hostname: fawkes.rexden.us
      network:
        - [ "private_network", { ip: "192.168.33.19" } ]
  - name: monitor_server
    driver_config:
      box: bento/centos-7.1
      vm_hostname: norris.rexden.us
      network:
        - [ "private_network", { ip: "192.168.33.21" } ]
  - name: log_server
    driver_config:
      box: bento/centos-7.1
      customize:
        memory: 2048
      vm_hostname: buckbeak.rexden.us
      network:
        - [ "private_network", { ip: "192.168.33.20" } ]
  - name: centos
    driver_config:
      box: bento/centos-7.1
      vm_hostname: test-centos
      network:
        - [ "private_network", { ip: "192.168.33.231" } ]

#driver:
#  name: docker
#  require_chef_omnibus: true
#  memory: 1024k
#  binary: /bin/docker
#  use_sudo: true
#  sudo_command: "/bin/sudo -E"

provisioner:
  #name: chef_solo
  name: chef_zero

#platforms:
#- name: ark_server
#    driver_config:
#      image: "centos/7"
#      platform: "rhel"

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

#platforms:
#  - name: ubuntu-14.04
#  - name: centos-7.1

suites:
  - name: default
    excludes: [ 'ark_server', 'monitor_server', 'log_server' ]
    run_list:
      - recipe[rexden]
      - recipe[rexden::_dev_vagrant]
    attributes:
      rexden:
        syslog_server: 192.168.33.20
        ark_server_name: fawkes.rexden.us
        ark_server_ip: 192.168.33.19
  - name: ark
    excludes: [ 'centos', 'monitor_server', 'log_server' ]
    driver:
      instance_name: ark_server
    run_list:
      - recipe[rexden::ark_server]
    attributes:
      rexden:
        ark_server_name: fawkes.rexden.us
        ark_server_ip: 192.168.33.19
  - name: monitor
    excludes: [ 'centos', 'ark_server', 'log_server' ]
    driver:
      instance_name: monitor_server
    run_list:
      - recipe[rexden::monitor_server]
    attributes:
      rexden:
        ark_server_name: fawkes.rexden.us
        ark_server_ip: 192.168.33.19
  - name: logs
    excludes: [ 'centos', 'ark_server', 'monitor_server' ]
    driver:
      instance_name: log_server
    run_list:
      - recipe[rexden::log_server]
    attributes:
      rexden:
        ark_server_name: fawkes.rexden.us
        ark_server_ip: 192.168.33.19
