name 'rexden'
maintainer 'David King'
maintainer_email 'david@rexden.us'
license 'all_rights'
description 'Installs/Configures rexden'
long_description 'Installs/Configures rexden'
version '0.1.0'

depends 'redhat_subscription_manager', '~> 0.1'
depends 'hostsfile'
depends 'yum-epel'
depends 'selinux'
depends 'firewall'
depends 'chef-client'
depends 'chef-splunk'
